### ISSUE TITLE
Yomichan no longer detects yomichan-forvo-server

### ISSUE THREAD

**Issue by Uzemdore** [jamesnicolas/yomichan-forvo-server#27]
I've been using yomi-chan-forvo-server for a year now and it's been a life saver.
I'm not sure if the issue is on my end, but sadly it seems to no longer work.

![57186ed8410232194b222c4e95983904](https://github.com/user-attachments/assets/e112dd4d-e51a-4497-89cb-ea5046bf951a)
![260dfa39917c7bd75192d3524ac17190](https://github.com/user-attachments/assets/8aeb9475-d0eb-4307-a66f-0d200a222eb5)

**Comment by SnadaffUmuu** [comment]
The same here. I updated the plugin to the last version in Anki and it stopped working, just like on [Uzemdore](https://github.com/Uzemdore) 's screenshot.

**Comment by eggvelyn** [comment]
I'm having the same issue unfortunately. This plugin is invaluable for language learners so I will hope this gets fixed soon! 🙏

**Comment by jamesnicolas** [comment]
Sorry for being ghosty but I believe this is related to https://github.com/jamesnicolas/yomichan-forvo-server/issues/13

Basically forvo has put their stuff behind cloudflare, which is a bot-protection service. I haven't been able to get around it.

**Comment by buryoutougen** [comment]
If it's any help, there's [this Anki add-on](https://github.com/realmayus/anki_forvo_dl) that also fetches audio from Forvo, it was fixed recently and it's working now even with CloudFlare enabled on Forvo. Perhaps it could be possible to look into its code to find a solution.

Edit: it seems to have stopped working today (18.08.2024), unfortunately.
Edit 2: looks like it's working again.

**Comment by jamesnicolas** [comment]
I'm trying these headers but still getting blocked by cloudflare

https://github.com/realmayus/anki_forvo_dl/pull/114/files

**Comment by buryoutougen** [comment]
I just checked, it isn't working again. It seems Forvo is constantly making some changes.

**Comment by dlmubs** [comment]
> I'm trying these headers but still getting blocked by cloudflare
> 
> https://github.com/realmayus/anki_forvo_dl/pull/114/files

would library like https://github.com/lexiforest/curl_cffi help to bypass cf verification?

**Comment by MinmusxMinmus** [comment]
> > I'm trying these headers but still getting blocked by cloudflare
> > https://github.com/realmayus/anki_forvo_dl/pull/114/files
> 
> would library like https://github.com/lexiforest/curl_cffi help to bypass cf verification?

I've made [a fork of the project](https://github.com/MinmusxMinmus/yomichan-forvo-server) and updated it with `curl_cffi` as suggested, and it seems to be getting around Cloudflare properly.  However, since the library isn't pure Python, vendoring it in is a bit more tricky so for now I'm just running the server separately for myself and I've abandoned the whole addon part. Perhaps someone more dedicated can figure out how to turn it into an Anki addon again?

**Comment by Musrar** [comment]
@MinmusxMinmus Sorry to mention you, but how could I set up the local server you linked? I'm a bit noob at it

**Comment by MinmusxMinmus** [comment]
> [@MinmusxMinmus](https://github.com/MinmusxMinmus) Sorry to mention you, but how could I set up the local server you linked? I'm a bit noob at it

I've configured it to run with [uv](https://docs.astral.sh/uv/) or as a [Docker](https://www.docker.com/) container, so as long as you have either installed it should be pretty simple.  I've updated the repo with instructions on how to use it, check them out!

The server should behave the same as the original addon's, so the rest of the config (configuring audio playback sources etc) should work out of the box.
